# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Gogo Code
email: info@jumpstart.ge
description: Gogo Code is a program to teach teenage girls in Georgia the basics of computer programming and encourage participation in STEM fields.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://gogocode.jumpstart.ge/" # the base hostname & protocol for your site
github_username: JumpStartGeorgia

# Build settings
markdown: kramdown

# gems:
#   - octopress-autoprefixer
