---
title: Gogo Code
timezone: Asia/Tbilisi
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  eng-stories:
    title: eng-stories
    output: true
    permalink: "/:categories/stories/:title"
  ka-stories:
    title: ka-stories
    output: true
    permalink: "/:categories/stories/:title"
email: info@jumpstart.ge
description: Gogo Code is a program to teach teenage girls in Georgia the basics of
  computer programming and encourage participation in STEM fields.
baseurl: 
url: http://gogocode.jumpstart.ge/
github_username: JumpStartGeorgia
markdown: kramdown
excerpt_separator: "<!--more-->"
permalink: pretty

defaults:
  - 
    scope:
      path: ""
      type: eng-stories
    values:
      layout: english_story 
      categories:
        - en
      video: "--" 
  - 
    scope:
      path: ""
      type: ka-stories
    values:
      layout: georgian_story
      categories:
        - ka 