---
title: Gogo Code
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  "-stories-posts":
    title: Stories
    output: true
  uploads:
    title: Uploads
    output: true
email: info@jumpstart.ge
description: Gogo Code is a program to teach teenage girls in Georgia the basics of
  computer programming and encourage participation in STEM fields.
baseurl: 
url: http://gogocode.jumpstart.ge/
github_username: JumpStartGeorgia
markdown: kramdown
