---
title: Gogo Code
timezone: Asia/Tbilisi
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  eng-stories:
    title: eng-stories
    output: true
    permalink: "/:categories/stories/:title"
  ka-stories:
    title: ka-stories
    output: true
    permalink: "/:categories/stories/:title"
defaults:
- scope:
    path: ''
    type: eng-stories
  values:
    layout: english_story
    categories:
    - en
    slug: Add english name of the story here / use small letters
    video: Add your video link here.
    header_image: Main picture of the story, that will appear on the stories page.
    popup_image: Popup image, that could be viewed full size on the story page by
      clicking on it.
    slideshow: Convert this field to Object, then add images - each key should have
      an unique name that contains word 'image' (s1_image, s2_image).
- scope:
    path: ''
    type: ka-stories
  values:
    layout: georgian_story
    categories:
    - ka
    slug: დაამატე ამბის ინგლისური სახელი აქ / გამოიყენე მხოლოდ პატარა ასოები
    video: დაამატე შენი ვიდეოს ლინკი აქ.
    header_image: მთავარი სურათი ამბის, რომელიც ამბების ჩამონათვალში გამოჩნება.
    popup_image: Popup სურათი, რომელიც იქნება ამბის გვერდზე და სრული ზომით გამოჩნდება
      დაკლიკვის შემდეგ.
    slideshow: აქციე ეს ველი Object-ად, შემდეგ დაამატე სურათები - ყოველ key-ს უნდა
      ჰქონდეს უნიკალური სახელი, რომელიც შეიცავს სიტყვა 'image'-ს (s1_image, s2_image).
email: info@jumpstart.ge
description: Gogo Code is a program to teach teenage girls in Georgia the basics of
  computer programming and encourage participation in STEM fields.
baseurl: 
url: http://gogocode.jumpstart.ge/
github_username: JumpStartGeorgia
markdown: kramdown
excerpt_separator: "<!--more-->"
permalink: pretty
video_en: Add your video link here.
header_image_en: Main picture of the story, that will appear on the stories page.
popup_image_en: Popup image, that could be viewed full size on the story page by clicking
  on it.
slideshow_en: Convert this field to Object, then add images - each key should have
  an unique name that contains word 'image' (s1_image, s2_image).
video_ka: დაამატე შენი ვიდეოს ლინკი აქ.
header_image_ka: მთავარი სურათი ამბის, რომელიც ამბების ჩამონათვალში გამოჩნება.
popup_image_ka: Popup სურათი, რომელიც იქნება ამბის გვერდზე და სრული ზომით გამოჩნდება
  დაკლიკვის შემდეგ.
slideshow_ka: აქციე ეს ველი Object-ად, შემდეგ დაამატე სურათები - ყოველ key-ს უნდა
  ჰქონდეს უნიკალური სახელი, რომელიც შეიცავს სიტყვა 'image'-ს (s1_image, s2_image).
gems:
- jekyll-redirect-from  