---
title: Gogo Code
timezone: Asia/Tbilisi
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  eng-blog:
    title: eng-blog
    output: true
    permalink: "/:categories/blog/:year/:month/:day/:title.html."
    slideshow:
    - 
  ka-blog:
    title: ka-blog
    output: true
    permalink: "/:categories/blog/:year/:month/:day/:title.html."
email: info@jumpstart.ge
description: Gogo Code is a program to teach teenage girls in Georgia the basics of
  computer programming and encourage participation in STEM fields.
baseurl: 
url: http://gogocode.jumpstart.ge/
github_username: JumpStartGeorgia
markdown: kramdown
