---
title: Gogo Code
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  eng-blog:
    title: eng-blog
    output: true
  ka-blog:
    title: ka-blog
    output: true
email: info@jumpstart.ge
description: Gogo Code is a program to teach teenage girls in Georgia the basics of
  computer programming and encourage participation in STEM fields.
baseurl: 
url: http://gogocode.jumpstart.ge/
github_username: JumpStartGeorgia
markdown: kramdown
permalink: ":slug/blog/:categories/:year/:month/:day/:title.html."
